<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Simple HttpErrorPages | MIT X11 License | https://github.com/AndiDittrich/HttpErrorPages -->

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <title>We've got some trouble | <?php echo $v_code; ?> - <?php echo $v_title; ?></title>

    <style type="text/css"><?php echo $css; ?></style>
</head>

<body>
    <div class="cover">
        <h1><?php echo $v_title; ?> <small>Error <?php echo $v_code; ?></small></h1>
        <p class="lead"><?php echo $v_message; ?></p>
    </div>
    
    <?php if (!empty($v_footer)){ ?>
    <footer>
        <p><?php echo $v_footer; ?></p>
    </footer>
    <?php } ?>
</body>
</html>
